name: calicost
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.10
  - numpy==1.24.4
  - scipy==1.11.3
  - samtools==1.18
  - bcftools==1.18
  - cellsnp-lite
  - snakemake
  - lemon